### ISSUE TITLE
help

### ISSUE THREAD

**Issue by XliOK** [bsarkar321/madrona_rl_envs#2]
Excuse me, I have completed all the steps in the Installation section as per the README.md instructions. If I want to start the hanabi project to test the simulation game, what should I do next? Which command should I use to start it?

**Comment by bsarkar321** [comment]
Hi! Sorry, I didn't receive an email notification for this issue. You can look inside the Hanabi-specific subfolder, which contains a README with examples for testing the simulation [here](https://github.com/bsarkar321/madrona_rl_envs/blob/main/src/hanabi_env/README.org).
